language: java

branches:
  only:
    - master

jdk:
  - oraclejdk8

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"

script: "mvn deploy --settings target/travis/settings.xml -Dsettings.security=target/travis/settings-security.xml"

after_success:
  - mvn cobertura:cobertura coveralls:cobertura
