language: java

branches:
  only:
    - master

jdk:
  - oraclejdk8

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"

script: "mvn clean install"

after_success:
  - mvn cobertura:cobertura coveralls:cobertura
